# Generated by Django 5.1.1 on 2024-09-05 15:45

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите вашу почту",
                        max_length=150,
                        unique=True,
                        verbose_name="почта",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Введите ваше имя",
                        max_length=150,
                        null=True,
                        verbose_name="имя пользователя",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите дополнительную информацию",
                        null=True,
                        verbose_name="описание",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Введите ваш номер телефона",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="телефон",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Выберите аватар",
                        null=True,
                        upload_to="users/avatars",
                        verbose_name="аватар",
                    ),
                ),
                (
                    "is_content_manager",
                    models.BooleanField(default=False, verbose_name="админ"),
                ),
                (
                    "is_moderator",
                    models.BooleanField(default=False, verbose_name="модератор"),
                ),
                (
                    "is_banned",
                    models.BooleanField(default=False, verbose_name="Забанен"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "permissions": [
                    (
                        "can_set_user_inactive",
                        "Can blocked user (bool is_active = False)",
                    )
                ],
            },
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания токена",
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Token"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="токен для восстановления пароля",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="токен для восстановления пароля",
                    ),
                ),
            ],
        ),
    ]
