# Generated by Django 5.1.1 on 2024-09-09 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название картинки",
                        max_length=150,
                        unique=True,
                        verbose_name="картинка-название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание картинки",
                        null=True,
                        verbose_name="Описание картинки",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="content/photo",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "картинка",
                "verbose_name_plural": "картинки",
            },
        ),
        migrations.CreateModel(
            name="ContentText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название текстового блока",
                        max_length=150,
                        unique=True,
                        verbose_name="контент-название",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="введите тело текстового блока",
                        verbose_name="тело текстового блока",
                    ),
                ),
            ],
            options={
                "verbose_name": "контент",
                "verbose_name_plural": "контент",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.SmallIntegerField(
                        help_text="Введите номер столика", verbose_name="Номер столика"
                    ),
                ),
                (
                    "places",
                    models.SmallIntegerField(
                        default=4,
                        help_text="Введите число сидячих мест у столика",
                        verbose_name="Число сидячих мест у столика",
                    ),
                ),
                (
                    "flour",
                    models.SmallIntegerField(
                        default=1,
                        help_text="Введите этаж нахождения столика",
                        verbose_name="Этаж нахождения столика",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="обычный столик",
                        help_text="Введите описание столика",
                        verbose_name="Описание столика",
                    ),
                ),
            ],
            options={
                "verbose_name": "столик",
                "verbose_name_plural": "столики",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_field",
                    models.DateField(
                        help_text="введите дата бронирования",
                        verbose_name="дата бронирования",
                    ),
                ),
                (
                    "time_start",
                    models.TimeField(
                        help_text="введите начало бронирования",
                        verbose_name="начало бронирования",
                    ),
                ),
                (
                    "time_end",
                    models.TimeField(
                        help_text="введите конец бронирования",
                        verbose_name="конец бронирования",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="введите активно ли бронирование",
                        verbose_name="активно ли бронирование",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания бронирования",
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="столик",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table",
                        to="restaurant.table",
                        verbose_name="столик",
                    ),
                ),
            ],
            options={
                "verbose_name": "бронирование",
                "verbose_name_plural": "бронирования",
            },
        ),
    ]
