# Generated by Django 5.1.1 on 2024-09-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="places",
            field=models.SmallIntegerField(
                default=2,
                help_text="Введите число бронируемых мест",
                verbose_name="Число бронируемых мест",
            ),
        ),
    ]
