# Generated by Django 5.1.1 on 2024-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_booking_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="notification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Не оповещать"),
                    (1, "За час"),
                    (2, "За два часа"),
                    (3, "За три часа"),
                ],
                default=0,
                verbose_name="Оповещение",
            ),
        ),
    ]
