# Generated by Django 5.1.1 on 2024-09-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_booking_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.SmallIntegerField(
                help_text="Введите номер столика",
                unique=True,
                verbose_name="Номер столика",
            ),
        ),
    ]
