# Generated by Django 5.1.1 on 2024-09-13 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_booking_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания токена",
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Token"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="токен для восстановления пароля",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_token",
                        to="restaurant.booking",
                        verbose_name="токен для подтверждения бронирования",
                    ),
                ),
            ],
        ),
    ]
