# Generated by Django 5.1.1 on 2024-09-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_bookingtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contentlink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название ссылки",
                        max_length=50,
                        unique=True,
                        verbose_name="название ссылки",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="введите текст ссылки",
                        max_length=50,
                        unique=True,
                        verbose_name="текст ссылки",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="введите адрес ссылки",
                        max_length=150,
                        verbose_name="адрес ссылки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание ссылки",
                        verbose_name="описание ссылки",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="введите название параметра",
                        max_length=50,
                        unique=True,
                        verbose_name="название параметра",
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        help_text="введите значение параметра",
                        max_length=150,
                        verbose_name="значение параметра",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание параметра",
                        verbose_name="описание параметра",
                    ),
                ),
            ],
        ),
    ]
