# Generated by Django 5.1.1 on 2024-09-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_contentlink_contentparameters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentlink",
            options={"verbose_name": "ссылка", "verbose_name_plural": "ссылки"},
        ),
        migrations.AlterModelOptions(
            name="contentparameters",
            options={"verbose_name": "параметр", "verbose_name_plural": "параметры"},
        ),
        migrations.AddField(
            model_name="booking",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите примечания к бронированию",
                null=True,
                verbose_name="Примечания",
            ),
        ),
    ]
