# Generated by Django 5.1.1 on 2024-09-14 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_alter_contentlink_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="Введите текст вопроса", verbose_name="Текст вопроса"
                    ),
                ),
                (
                    "sign",
                    models.CharField(
                        help_text="Введите подпись под вопросом",
                        max_length=50,
                        verbose_name="Подпись",
                    ),
                ),
                (
                    "moderated",
                    models.BooleanField(
                        default=False,
                        help_text="Введите признак проверки",
                        verbose_name="Проверен",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True,
                        help_text="Введите ответ на вопрос",
                        null=True,
                        verbose_name="Ответ на вопрос",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания",
                        verbose_name="дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        help_text="Введите текст отзыва", verbose_name="Текст отзыва"
                    ),
                ),
                (
                    "sign",
                    models.CharField(
                        help_text="Введите подпись под отзывом",
                        max_length=50,
                        verbose_name="Подпись",
                    ),
                ),
                (
                    "grade",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Не оповещать"),
                            (1, "За час"),
                            (2, "За два часа"),
                            (3, "За три часа"),
                        ],
                        default=5,
                        verbose_name="Оповещение",
                    ),
                ),
                (
                    "moderated",
                    models.BooleanField(
                        default=False,
                        help_text="Введите признак проверки",
                        verbose_name="Проверен",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True,
                        help_text="Введите ответ на вопрос",
                        null=True,
                        verbose_name="Ответ на вопрос",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="введите дату создания",
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="введите дату изменения",
                        verbose_name="дата изменения",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="пользователь",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
            },
        ),
    ]
