# Generated by Django 5.1.1 on 2024-09-17 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0009_questions_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                help_text="выберите столик",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to="restaurant.table",
                verbose_name="столик",
            ),
        ),
        migrations.AlterField(
            model_name="bookingtoken",
            name="booking",
            field=models.ForeignKey(
                help_text="токен для восстановления пароля",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_token",
                to="restaurant.booking",
                verbose_name="бронирование",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="answer_text",
            field=models.TextField(
                blank=True,
                help_text="Введите ответ на отзыв",
                null=True,
                verbose_name="Ответ на отзыв",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="grade",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Не оповещать"),
                    (1, "За час"),
                    (2, "За два часа"),
                    (3, "За три часа"),
                ],
                default=5,
                verbose_name="Оценка",
            ),
        ),
    ]
