# Generated by Django 5.1.1 on 2024-09-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_alter_booking_table_alter_bookingtoken_booking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="notification",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Не оповещать"),
                    (1, "За час"),
                    (2, "За два часа"),
                    (3, "За три часа"),
                ],
                default=0,
                verbose_name="Оповещение на Telegram (если указан при регистрации)",
            ),
        ),
    ]
